export const mockPosts = [
  {
    id: "1",
    username: "JMike Nisien",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A beautiful sunrise.",
  },
  {
    id: "2",
    username: "Jana Smith",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A motivational video.",
  },
  {
    id: "3",
    username: "Alice Brown",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A lovely garden.",
  },
  {
    id: "4",
    username: "Michael Johnson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "Enjoying the beach on a sunny day.",
  },
  {
    id: "5",
    username: "Emily Davis",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A quiet evening at home with a good book.",
  },
  {
    id: "6",
    username: "David Lee",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "The city skyline at dusk.",
  },
  {
    id: "7",
    username: "Sophia Clark",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "Baking a homemade apple pie.",
  },
  {
    id: "8",
    username: "William Hall",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "Morning coffee and a fresh croissant.",
  },
  {
    id: "9",
    username: "Isabella Moore",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A walk through the autumn leaves.",
  },
  {
    id: "10",
    username: "Ethan Wilson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "Hiking through the mountains.",
  },
  {
    id: "11",
    username: "Ava Anderson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A time-lapse of the sunset over the ocean.",
  },
  {
    id: "12",
    username: "Mason Thomas",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "Family dinner on a special occasion.",
  },
  {
    id: "13",
    username: "Olivia Harris",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A relaxing day at the spa.",
  },
  {
    id: "14",
    username: "James White",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "Lush green fields after a summer rain.",
  },
  {
    id: "15",
    username: "Lily Martinez",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A peaceful forest walk in the early morning.",
  },
  {
    id: "16",
    username: "Benjamin Garcia",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A behind-the-scenes look at a music video shoot.",
  },
  {
    id: "17",
    username: "Charlotte Rodriguez",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A stunning flower arrangement.",
  },
  {
    id: "18",
    username: "Daniel Perez",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A delicious homemade pasta dinner.",
  },
  {
    id: "19",
    username: "Zoe Wilson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A cozy fireplace on a cold winter's night.",
  },
  {
    id: "20",
    username: "Jack Johnson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "Jumping off a cliff into crystal clear water.",
  },
  {
    id: "21",
    username: "Mia Brown",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A cute puppy playing in the park.",
  },
  {
    id: "22",
    username: "Alexander Lee",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A snowy mountain landscape.",
  },

  {
    id: "23",
    username: "Amelia Clark",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A breathtaking view from a hiking trail.",
  },
  {
    id: "24",
    username: "Lucas Moore",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A skateboard trick at the local park.",
  },
  {
    id: "25",
    username: "Ella Hall",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A picnic in the park with friends.",
  },
  {
    id: "26",
    username: "Samuel Taylor",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A quiet fishing trip by the lake.",
  },
  {
    id: "27",
    username: "Grace Walker",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "An art gallery visit on a rainy day.",
  },
  {
    id: "28",
    username: "Daniel Young",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A drone footage of the city skyline at night.",
  },
  {
    id: "29",
    username: "Liam Harris",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A day at the zoo with the family.",
  },
  {
    id: "30",
    username: "Aria Martinez",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A gorgeous sunset on the beach.",
  },
  {
    id: "31",
    username: "Leo Scott",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A camping trip under the stars.",
  },
  {
    id: "32",
    username: "Chloe Lewis",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A bowl of fresh fruit in the morning sunlight.",
  },
  {
    id: "33",
    username: "Gabriel Walker",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "An afternoon at a live concert.",
  },
  {
    id: "34",
    username: "Natalie Allen",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A peaceful sunrise over the ocean.",
  },
  {
    id: "35",
    username: "Ryan King",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A day spent at the amusement park.",
  },
  {
    id: "36",
    username: "Victoria Roberts",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A cozy autumn afternoon with a warm drink.",
  },
  {
    id: "37",
    username: "Isaac Walker",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A relaxing day at the beach with friends.",
  },
  {
    id: "38",
    username: "Sophie Campbell",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A peaceful walk through the botanical garden.",
  },
  {
    id: "39",
    username: "Maximus Wright",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A beautiful view of the mountains from my backyard.",
  },
  {
    id: "40",
    username: "Olivia Martinez",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "The first flowers of spring in full bloom.",
  },
  {
    id: "41",
    username: "Elijah Davis",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A serene lake surrounded by tall trees.",
  },
  {
    id: "42",
    username: "Scarlett Taylor",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A funny dog doing tricks in the backyard.",
  },
  {
    id: "43",
    username: "Henry Wilson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "An evening walk with my dog.",
  },
  {
    id: "44",
    username: "Lily Scott",
    userPhoto: "/https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A delicious plate of homemade sushi.",
  },
  {
    id: "45",
    username: "Maddox Lee",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A quiet Sunday afternoon at the park.",
  },
  {
    id: "46",
    username: "Charlotte Walker",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A funny blooper from our latest family video.",
  },
  {
    id: "47",
    username: "Jack Anderson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A day at the lake with friends and family.",
  },
  {
    id: "48",
    username: "Ella Harris",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A beautiful sunset over the desert.",
  },
  {
    id: "49",
    username: "Zachary Thompson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A camping trip with a beautiful view of the mountains.",
  },
  {
    id: "50",
    username: "Harper Moore",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A quiet moment with a cup of tea and a good book.",
  },
  {
    id: "51",
    username: "Nathaniel Clark",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A bustling street market in the city.",
  },
  {
    id: "52",
    username: "Penelope Rodriguez",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "Exploring the city on a rainy day.",
  },
  {
    id: "53",
    username: "Aidan Harris",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A relaxing afternoon at the beach with a good book.",
  },
  {
    id: "54",
    username: "Chloe Scott",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A beautiful dog running through the fields.",
  },
  {
    id: "55",
    username: "Christopher Green",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A scenic hike through the forest.",
  },
  {
    id: "56",
    username: "Hannah White",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A fun beach day with friends.",
  },
  {
    id: "57",
    username: "Jackson Adams",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A winter hike in the snow.",
  },
  {
    id: "58",
    username: "Avery Walker",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A fall day in the park with my dog.",
  },
  {
    id: "59",
    username: "Carter Evans",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A delicious homemade pizza with fresh ingredients.",
  },
  {
    id: "60",
    username: "Addison Allen",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A cozy evening at home with my favorite blanket.",
  },
  {
    id: "61",
    username: "Lillian King",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A vibrant sunset over the city skyline.",
  },
  {
    id: "62",
    username: "Grayson Hall",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A fun time-lapse of a construction project.",
  },
  {
    id: "63",
    username: "Ariana Moore",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A perfect bowl of ramen.",
  },
  {
    id: "64",
    username: "Isaac Taylor",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A clear blue sky over the ocean.",
  },
  {
    id: "65",
    username: "Madison Brown",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A compilation of fun moments with friends.",
  },
  {
    id: "66",
    username: "Gabriella Lee",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A beautiful road trip through the mountains.",
  },
  {
    id: "67",
    username: "Oliver Roberts",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A peaceful walk through a quiet town square.",
  },
  {
    id: "68",
    username: "Riley Anderson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A stunning fall sunset in the forest.",
  },
  {
    id: "69",
    username: "Ella White",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A slow-motion video of a dog jumping in the air.",
  },
  {
    id: "70",
    username: "Sebastian Green",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A scenic view of the coastline.",
  },

  {
    id: "71",
    username: "Ella Roberts",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A delicious spread of fresh pastries.",
  },
  {
    id: "72",
    username: "Jasper Thomas",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A quiet evening with a glass of wine and some cheese.",
  },
  {
    id: "73",
    username: "Archer Clark",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A funny fail compilation with friends.",
  },
  {
    id: "74",
    username: "Isabel Lewis",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A breathtaking mountain landscape.",
  },
  {
    id: "75",
    username: "Harrison White",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A snowy forest after a heavy snowfall.",
  },
  {
    id: "76",
    username: "Lena Scott",
    uuserPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A time-lapse of the sunrise over the mountains.",
  },
  {
    id: "77",
    username: "Noah King",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A casual dinner with friends.",
  },
  {
    id: "78",
    username: "Mia Green",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A peaceful boat ride on the lake.",
  },
  {
    id: "79",
    username: "Landon Perez",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A walk through the city streets at night.",
  },
  {
    id: "80",
    username: "Quinn Anderson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A homemade batch of chocolate chip cookies.",
  },
  {
    id: "81",
    username: "Harley Davis",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A morning jog through the park.",
  },
  {
    id: "82",
    username: "Natalia Harris",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A fun day out with friends at the fair.",
  },
  {
    id: "83",
    username: "Sasha Robinson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A funny video of a cat chasing its tail.",
  },
  {
    id: "84",
    username: "Colton Allen",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A beautiful sunset over the mountains.",
  },
  {
    id: "85",
    username: "Reagan Clark",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A peaceful countryside road at dawn.",
  },
  {
    id: "86",
    username: "Harper Thomas",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A scenic drone shot over the ocean.",
  },
  {
    id: "87",
    username: "Jaxon Moore",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A fun day at the beach with family.",
  },
  {
    id: "88",
    username: "Brooklyn Scott",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A quiet evening in the city.",
  },
  {
    id: "89",
    username: "Evan Roberts",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A beautiful garden filled with flowers.",
  },
  {
    id: "90",
    username: "Mia Scott",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A timelapse of the flowers blooming in the garden.",
  },
  {
    id: "91",
    username: "Hudson Walker",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A lazy Sunday afternoon in the park.",
  },
  {
    id: "92",
    username: "Lola Anderson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A late-night study session with coffee.",
  },
  {
    id: "93",
    username: "Beckett Harris",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A delicious plate of homemade pancakes.",
  },
  {
    id: "94",
    username: "Serena Lee",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A relaxing afternoon in the garden.",
  },
  {
    id: "95",
    username: "Zane Davis",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A fun day at the carnival with friends.",
  },
  {
    id: "96",
    username: "Piper Wilson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "video",
    description: "A skateboarding trick at the park.",
  },
  {
    id: "97",
    username: "Kai Anderson",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A beautiful sunrise hike through the mountains.",
  },
  {
    id: "98",
    username: "Ruby Taylor",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A quiet afternoon at the coffee shop.",
  },
  {
    id: "99",
    username: "Milo Scott",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A calm boat ride on the lake at dusk.",
  },
  {
    id: "100",
    username: "Holly Walker",
    userPhoto: "https://picsum.photos/100?random=1",
    mediaUrl: "https://picsum.photos/500?random=2",
    mediaType: "image",
    description: "A peaceful nature walk through the forest.",
  },
];